// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njrccrvfsnmvnbwvlvey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qcmNjcnZmc25tdm5id3ZsdmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTQ4NjEsImV4cCI6MjA2MjczMDg2MX0.BsxMyKpmDqcxgMVkJeLNT0JAKj5epWTJnUOZx6auPmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);